---
- name: Install custom software
  hosts: localhost
  remote_user: root

  tasks:
    - name: Install bat
      community.general.pacman:
        name: bat
        state: present

    - name: Install dolphin
      community.general.pacman:
        name: dolphin
        state: present

    - name: Install gwenview
      community.general.pacman:
        name: gwenview
        state: present

    - name: Install helix
      community.general.pacman:
        name: helix
        state: present

    - name: Install fish
      community.general.pacman:
        name: fish
        state: present

    - name: Install npm
      community.general.pacman:
        name: npm
        state: present

    - name: Install pipewire
      community.general.pacman:
        name: pipewire
        state: present
    
    - name: Install pipewire-audio
      community.general.pacman:
        name: pipewire-audio
        state: present

    - name: Install ripgrep
      community.general.pacman:
        name: ripgrep
        state: present

    - name: Install sudo
      community.general.pacman:
        name: sudo
        state: present
